### ISSUE TITLE
Difficulties on macOS

### ISSUE THREAD

**Issue by schmidhauser** [pointtonull/anki-external_editor#1]
Great idea. Many thanks. Unfortunately it does not work on macOS 10.14 with Anki 2.1.19. 

* If I set the config to (say) `"editor": "open -t"`, TextEdit opens. But if I change anything and save and close the file, the changes are not reflected in Anki. Ditto with (e.g.) `"editor": "open -a textmate"`.

* If I set the config to `"editor": "atom"` or  `"editor": "mate"` (for TextMate), nothing happens.

* The standard shortcut to open the HTML editor is `⇧⌘X` – not `⌘X`, as you say in your description. However, I think it could actually be very useful to assign a different shortcut to open one’s personal editor, so perhaps you could change the standard shortcut to `⌘X`?

**Comment by pointtonull** [comment]
Hi!
I am sorry for the delay. I did not catch the notification.
It's too late right now (uk time), but I'll be working on your suggestions during the week.

Thank you
