### ISSUE TITLE
something useful?

### ISSUE THREAD

**Issue by ijgnd** [pointtonull/anki-external_editor#3]
I have uploaded my fork [here](https://github.com/ijgnd/anki__external_latex_editor/commits/master) and [here](https://ankiweb.net/shared/info/1184418999). I have added an AGPL license because I took your code from ankiweb. I assume you are ok with this?

If your project is AGPL and you find anything useful in my code please reuse it. It should be instructive how a software professional transforms my code and your code was really useful for me so it would be great if I could "give back".

What I changed:

- I added a function to send selected text to my text editor. I want to improve my programming skills, so this might be useful. 
- I saw that someone wants to save back plain text into a field (e.g. for latex) which sounds useful. So I tried to find a solution. It seems to work but it's ugly and it probably doesn't handle all cases well. I copied over an undo function from a different add-on so I need to re-check it. [Here's a screencast](https://github.com/ijgnd/anki__external_latex_editor/blob/master/screencasts/latex_in_vscode.gif) of how the latex editing works.
- I changed how the editor is detected. It works better for me but it's much less user friendly.

&nbsp;

It would also make sense to edit the front template, back template or the styling in an external text editor, especially with the add-on you already have installed. I have an add-on that uses a js editor to edit templates. For this I have some working code that grabs the content of the relevant fields in the clayout dialog, see [this code](https://github.com/ijgnd/anki__editor_edit_html_extended/blob/master/src/clayout_adjust.py). Again it would be instructive to see how a professional improves my code.

**Comment by pointtonull** [comment]
Nice.
I added an Apache License to my repo. I am fine changing it to AGPL if it makes contribution easier.
Just created a PR, I'll assign it to you so you can check it. I re-implemented the executable detection, added some proper testing, and a Makefile to keep all organized.
Checking your repo now.

**Comment by pointtonull** [comment]
Well, I could not add you as reviewer, this is the PR I was talking about: https://github.com/pointtonull/anki-external_editor/pull/4

**Comment by pointtonull** [comment]
I love the idea of inserting the text, and calling the editor from context menu. Really useful.

**Comment by pointtonull** [comment]
Beware, in the description of your extension, the link to config.md is broken.

**Comment by ijgnd** [comment]
your changes look very good. 

You forgot to update your readme.md which still has only ["code"](https://github.com/pointtonull/anki-external_editor/blame/master/config.md#L7) instead of "code -w". Manually setting the "editor" to "code" has priority over your built-ins so it wouldn't work.

Thanks for adding the license. That's great for me. Now I can directly reuse your code from github. But when it comes to Anki add-ons you are limiting yourself. Most add-ons use the AGPL license, probably because they are often reusing code from Anki itself, at least that's what I do, e.g. in my latex fork. So if you ever want to reuse some of this code you can't upload it to this github repo (and I hope that you'll find something useful in it). Though I recently learned that some companies ban all AGPL code from work computers which might make it impractical for you.

> Beware, in the description of your extension, the link to config.md is broken.

Thanks, fixed. I totally missed this. ankiweb detects "config.md" as a domain and transforms the text to a link automatically.
